apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb-rc
spec:
  replicas: 3
  selector:
    env: production
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
        region: in
    spec:
      containers:
        - name: myweb-con
          image: httpd

